=== djfdyuruiry/cnc-new-construction-options/cmake/nco-rules-json-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "NCO metadata for game rules",
  "description": "Metadata for a section of a rules.ini file",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "section": {
      "type": "string",
      "description": "INI identifier for the section"
    },
    "ini_comment": {
      "type": "string",
      "description": "Description of the section to be displayed above it in the INI file"
    },
    "comment": {
      "type": "string",
      "description": "Description of the section as markdown"
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the rule"
          },
          "type": {
            "type": "string",
            "enum": [
              "int",
              "bool",
              "float",
              "fixed"
            ],
            "description": "Type of the rule value"
          },
          "default": {
            "description": "Default value for the rule"
          },
          "comment": {
            "type": "string",
            "description": "Explanation of the rule"
          },
          "implemented": {
            "type": "boolean",
            "description": "Is behavior for this rule actually implemented yet?"
          }
        },
        "required": [
          "name",
          "type",
          "default"
        ]
      }
    }
  },
  "required": [
    "section",
    "ini_comment",
    "comment",
    "rules"
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/03.Game.Factories.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Factories",
  "ini_comment": "Factory behavior (barracks, weapons factory etc.)",
  "comment": "Factory behavior (barracks, weapons factory etc.).",
  "rules": [
    {
      "name": "ProductionStepsPerTick",
      "type": "int",
      "default": 1,
      "comment": "The amount of building progress that is made on each game tick. There are 15 ticks in second, so this value multiplied by 15 is the amount of progress that will be made in one second."
    },
    {
      "name": "FactoryCountStepMultiplier",
      "type": "float",
      "default": 1.0,
      "comment": "The multiplier to apply for each factory present, so if you have two Barracks and set this to `1.0`"
    },
    {
      "name": "TotalProductionSteps",
      "type": "int",
      "default": 108,
      "comment": "The amount of steps required to build a thing, this divided by `ProductionStepsPerTick` is the time in game ticks required. For example: if `ProductionStepsPerTick` was 2 and `TotalProductionSteps` was 30 - it would take 15 game ticks (or 1 second)."
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/02.Game.Map.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Map",
  "ini_comment": "Building placement rules and tiberium behavior",
  "comment": "Building placement rules and tiberium behavior.",
  "rules": [
    {
      "name": "PreventBuildingInShroud",
      "type": "bool",
      "default": true,
      "comment": "Prevent a player from placing a building inside the shroud/fog of war."
    },
    {
      "name": "AllowBuildingBesideWalls",
      "type": "bool",
      "default": true,
      "comment": "Allow building structures off player walls."
    },
    {
      "name": "TiberiumGrows",
      "type": "bool",
      "default": true,
      "comment": "Tiberium cells will grow on the map."
    },
    {
      "name": "TiberiumSpreads",
      "type": "bool",
      "default": true,
      "comment": "Tiberium will spread to nearby cells."
    },
    {
      "name": "SlowTiberiumGrowthAndSpread",
      "type": "bool",
      "default": false,
      "comment": "Slows down tiberium spread and growth (half the default rate)"
    },
    {
      "name": "TiberiumGrowthRate",
      "type": "float",
      "default": 1.0,
      "comment": "Controls the rate of tiberium growth, note enabling `SlowTiberiumGrowthAndSpread` will half the set rate. _Note: excessive values may cause performance problems._"
    },
    {
      "name": "TiberiumSpreadRate",
      "type": "float",
      "default": 1.0,
      "comment": "Controls the rate of tiberium spread, note enabling `SlowTiberiumGrowthAndSpread` will half the set rate. _Note: excessive values may cause performance problems._"
    },
    {
      "name": "TiberiumInfantryDamage",
      "type": "int",
      "default": 2,
      "comment": "The amount of damage infantry takes by walking across a cell of tiberium, if infantry type has the `ImmuneToTiberium` flag is set to `yes` then this is ignored for that type."
    },
    {
      "name": "TiberiumBlossomTreeDamage",
      "type": "int",
      "default": 5,
      "comment": "The amount of damage nearby units/infantry etc. take by when a blossom tree shoots tiberium in the air."
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/08.Game.House.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.House",
  "ini_comment": "House (GDI/NOD) specific behavior, mainly used to hide units/super powers from certain sides",
  "comment": "House (GDI/NOD) specific behavior, mainly used to hide units/super powers from certain sides.",
  "rules": [
    {
      "name": "HideTempleFromGdi",
      "type": "bool",
      "default": true,
      "comment": "Don't allow NOD construction yards captured by GDI to build a NOD Temple"
    },
    {
      "name": "HideObeliskFromGdi",
      "type": "bool",
      "default": true,
      "comment": "Don't allow NOD construction yards captured by GDI to build an Obelisk"
    },
    {
      "name": "HideApcFromNod",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "HideRocketLauncherFromNod",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "HideHelipadFromNod",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "HideAdvancedCommCenterFromNod",
      "type": "bool",
      "default": true,
      "comment": "Don't allow GDI construction yards captured by NOD to to build an Adv. Comm Center"
    },
    {
      "name": "OnlyGdiCanUseIonCannon",
      "type": "bool",
      "default": true,
      "comment": "Only allow GDI constructed Adv. Comm Center to grant the Ion Cannon superpower"
    },
    {
      "name": "OnlyNodCanUseNuke",
      "type": "bool",
      "default": true,
      "comment": "Only allow Nod constructed Temple of Nod to grant the Nuke superpower"
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/01.Game.Limits.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Limits",
  "ini_comment": "Internal game engine limits for map objects, scenario control etc. (not supported in Lua)",
  "comment": "This section allows you to change previously hardcoded limits in the game engine. These were originally capped due to memory constraints and to maintain good performance.<br/><br/>Default limits in Tiberian Dawn have been doubled in NCO.<br/><br/>**Note: Changing these in Lua has no effect, they can only be set via rules.ini**",
  "rules": [
    {
      "name": "InfantryMax",
      "type": "int",
      "default": 1000,
      "comment": "Maximum number of infantry"
    },
    {
      "name": "UnitsMax",
      "type": "int",
      "default": 1000,
      "comment": "Maximum number of units"
    },
    {
      "name": "AircraftMax",
      "type": "int",
      "default": 1000,
      "comment": "Maximum number of aircraft"
    },
    {
      "name": "BuildingsMax",
      "type": "int",
      "default": 1000,
      "comment": "Maximum number of buildings"
    },
    {
      "name": "FactoriesMax",
      "type": "int",
      "default": 64,
      "comment": "Maximum number of factories"
    },
    {
      "name": "HousesMax",
      "type": "int",
      "default": 24,
      "comment": "Maximum number of houses"
    },
    {
      "name": "AnimationsMax",
      "type": "int",
      "default": 400,
      "comment": "Maximum number of animations"
    },
    {
      "name": "BulletsMax",
      "type": "int",
      "default": 500,
      "comment": "Maximum number of bullets"
    },
    {
      "name": "TerrainMax",
      "type": "int",
      "default": 1000,
      "comment": "Maximum number of terrain object (trees etc.)"
    },
    {
      "name": "TeamsMax",
      "type": "int",
      "default": 120,
      "comment": "Maximum number of teams (instances of team types)"
    },
    {
      "name": "TeamTypesMax",
      "type": "int",
      "default": 120,
      "comment": "Maximum number of team types (reinforcements, teams for AI to build)"
    },
    {
      "name": "TriggersMax",
      "type": "int",
      "default": 160,
      "comment": "Maximum number of triggers"
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/11.Game.Superweapons.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Superweapons",
  "ini_comment": "Rules for superweapons in the game",
  "comment": "Change superweapon damage and recharge times.",
  "rules": [
    {
      "name": "AirStrikeRechargeTimeInMins",
      "type": "int",
      "default": 8,
      "comment": "How long an Air Strike takes to recharge, in minutes"
    },
    {
      "name": "IonCannonRechargeTimeInMins",
      "type": "int",
      "default": 10,
      "comment": "How long the Ion Cannon takes to recharge, in minutes"
    },
    {
      "name": "IonCannonDamage",
      "type": "int",
      "default": 600,
      "comment": "Ion Cannon direct hit damage"
    },
    {
      "name": "NuclearStrikeRechargeTimeInMins",
      "type": "int",
      "default": 14,
      "comment": "How long a Nuclear Strike takes to recharge, in minutes"
    },
    {
      "name": "NuclearStrikeDamage",
      "type": "int",
      "default": 1000,
      "comment": "Nuclear Strike direct hit damage"
    },
    {
      "name": "NuclearStrikeDamageRadius",
      "type": "int",
      "default": 4,
      "comment": "How big is the blast radius of a Nuclear Strike"
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/10.Game.Scenarios.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Scenarios",
  "ini_comment": "Rules for specific scenarios, used to modify the tech tree (TODO: Embed in scenario INI)",
  "comment": "Change game rules for specific single player scenarios, mainly used to modify the player tech tree.",
  "rules": [
    {
      "name": "SetBuildLevelTo1InGdiScenario2",
      "type": "bool",
      "default": true,
      "comment": "When player is in GDI mission 2 set the build level to 1"
    },
    {
      "name": "RenameTechCenterToPrisonInNodScenario3",
      "type": "bool",
      "default": true,
      "comment": "When playing NOD mission 3 rename Tech Centers to `Prison`"
    },
    {
      "name": "HideBazookaFromGdiUntilScenario8",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "HideRocketLauncherFromGdiUntilScenario9",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "HideSandbagFromGdiUntilScenario9",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "AllowNodToBuildAdvancedPowerInScenario12",
      "type": "bool",
      "default": true,
      "comment": "-"
    },
    {
      "name": "RequireTechCentreForStealthTankInNodScenario11",
      "type": "bool",
      "default": true,
      "comment": "-"
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/05.Game.Repair.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Repair",
  "ini_comment": "Repair behavior (Units and Aircraft)",
  "comment": "Repair behavior (Units and Aircraft).",
  "rules": [
    {
      "name": "BuildingRepairFactor",
      "type": "float",
      "default": 1.02,
      "comment": "Used along with strength step value to calculate the cost of a single repair step."
    },
    {
      "name": "BuildingRepairStrengthStep",
      "type": "int",
      "default": 5,
      "comment": "The amount of strength to give a building on each repair step."
    },
    {
      "name": "UnitRepairFactor",
      "type": "float",
      "default": 1.02,
      "comment": "Used along with strength step value to calculate the cost of a single repair step. (Cost / (MaxStrength / UnitRepairStrengthStep)) * UnitRepairFactor"
    },
    {
      "name": "UnitRepairStrengthStep",
      "type": "int",
      "default": 4,
      "comment": "The amount of strength to give a unit on each repair step."
    },
    {
      "name": "AircraftRepairFactor",
      "type": "float",
      "default": 1.02,
      "comment": "Used along with strength step value to calculate the cost of a single repair step. (Cost / (MaxStrength / AircraftRepairStrengthStep)) * AircraftRepairFactor"
    },
    {
      "name": "AircraftRepairStrengthStep",
      "type": "int",
      "default": 2,
      "comment": "The amount of strength to give a aircraft on each repair step."
    }
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/06.Game.Misc.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Misc",
  "ini_comment": "Miscellaneous rules for game engine behavior",
  "comment": "Rules that don't really fit into one category, covers a wide range of behavior.\n\n- Beta Features (Bibs, 3 point turns)\n- Allow using Skirmish/Multiplayer options in single player\n- Building behaviors",
  "rules": [
    {
      "name": "SmartDefense",
      "type": "bool",
      "default": false,
      "comment": "Human controlled units retaliate when they come under fire and they will also try to crush infantry if possible."
    },
    {
      "name": "TargetTrees",
      "type": "bool",
      "default": false,
      "comment": "Allow units to target trees."
    },
    {
      "name": "McvRedeployable",
      "type": "bool",
      "default": false,
      "comment": "Construction yards can be deconstructed by selecting them and clicking nearby on the map."
    },
    {
      "name": "SpawnVisceroids",
      "type": "bool",
      "default": false,
      "comment": "Spawn visceroids on the map."
    },
    {
      "name": "VehiclesDoThreePointTurns",
      "type": "bool",
      "default": false,
      "comment": "Make wheeled vehicles do 3 point turns."
    },
    {
      "name": "ShowBibsOnBuildings",
      "type": "bool",
      "default": true,
      "comment": "Show little dirt bibs on buildings (if turned off, overrides any rules for individual buildings)"
    },
    {
      "name": "ShowCivilianNames",
      "type": "bool",
      "default": false,
      "comment": "Show names of civilian structures and infantry - (C&C remastered seems to show the names regardless of this switch)"
    },
    {
      "name": "OnlyAllowNukeIfAllPartsHaveBeenCollected",
      "type": "bool",
      "default": true,
      "comment": "Only give the player the nuke at the end of Nod campaign if all crates were collected"
    },
    {
      "name": "OnlyAllowUsingOneNukePerScenario",
      "type": "bool",
      "default": true,
      "comment": "Remove the nuclear superpower after 1 shot"
    },
    {
      "name": "HelipadsAndAircraftBoughtSeparately",
      "type": "bool",
      "default": false,
      "comment": "Helipads do not come with a chopper, they are also cheaper."
    },
    {
      "name": "DestroyedBuildingsHaveSurvivors",
      "type": "bool",
      "default": true,
      "comment": "When a building is destroyed, should there be survivors left behind?"
    }
  ]
}
