=== djfdyuruiry/cnc-new-construction-options/cmake/nco-rules-json-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "NCO metadata for game rules",
  "description": "Metadata for a section of a rules.ini file",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "section": {
      "type": "string",
      "description": "INI identifier for the section"
    },
    "ini_comment": {
      "type": "string",
      "description": "Description of the section to be displayed above it in the INI file"
    },
    "comment": {
      "type": "string",
      "description": "Description of the section as markdown"
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the rule"
          },
          "type": {
            "type": "string",
            "enum": [
              "int",
              "bool",
              "float",
              "fixed"
            ],
            "description": "Type of the rule value"
          },
          "default": {
            "description": "Default value for the rule"
          },
          "comment": {
            "type": "string",
            "description": "Explanation of the rule"
          },
          "implemented": {
            "type": "boolean",
            "description": "Is behavior for this rule actually implemented yet?"
          }
        },
        "required": [
          "name",
          "type",
          "default"
        ]
      }
    }
  },
  "required": [
    "section",
    "ini_comment",
    "comment",
    "rules"
  ]
}

=== djfdyuruiry/cnc-new-construction-options/tiberiandawn/rules/07.Game.Multiplayer.json
{
  "$schema": "../../cmake/nco-rules-json-schema.json",
  "section": "Game.Multiplayer",
  "ini_comment": "Skirmish and network game rules",
  "comment": "Change behavior specific to skirmish and network games, some options will change how the setup screen for games behaves (max units, number of AI etc.)",
  "rules": [
    {
      "name": "StartUnitsWithBaseMax",
      "type": "int",
      "default": 12,
      "comment": "When bases are ON, the maximum number of starting units"
    },
    {
      "name": "StartUnitsWithoutBaseMax",
      "type": "int",
      "default": 50,
      "comment": "When bases are OFF, the maximum number of starting units"
    },
    {
      "name": "StartCreditsMax",
      "type": "int",
      "default": 10000,
      "comment": "Maximum number of starting credits for each player"
    }
  ]
}
